In [2]:
# Phase 3 — Dataset Collection & Understanding
# Import the libraries we need for this phase
import pandas as pd      
import numpy as np 
df = pd.read_csv('../data/crop_data.csv')
print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (2200, 8)

In [19]:
print(" FIRST 5 ROWS ")
df.head()

 FIRST 5 ROWS

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [7]:
print(" FIRST 2000 ROWS ")
df.head()

 FIRST 2000 ROWS

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [6]:
print(" LAST 5 ROWS ")
df.tail()

 LAST 5 ROWS

        N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [8]:
print(" DATASET INFO ")
df.info()

 DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB

In [9]:
# .columns shows all column names in the dataset
print(" COLUMN NAMES ")
print(df.columns.tolist())

 COLUMN NAMES
['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label']

In [10]:
# .dtypes shows the data type of each column
print("\n DATA TYPES ")
print(df.dtypes)

 DATA TYPES
N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label              str
dtype: object

In [11]:
# Print a clear explanation of each feature
feature_explanations = {
    "N  (Nitrogen)"      : "Promotes leafy, green growth. Essential for photosynthesis.",
    "P  (Phosphorus)"    : "Supports root development and flowering.",
    "K  (Potassium)"     : "Improves fruit quality and disease resistance.",
    "temperature"        : "Average temperature in °C. Crops have ideal temp ranges.",
    "humidity"           : "Relative humidity in %. Affects plant transpiration.",
    "ph"                 : "Soil acidity (0-14). Most crops prefer 6.0-7.5.",
    "rainfall"           : "Average rainfall in mm. Critical for water supply.",
    "label (TARGET)"     : "The crop name — this is what our model will PREDICT."
}

print(" FEATURE EXPLANATIONS \n")
for feature, explanation in feature_explanations.items():
    print(f"  {feature:25s} → {explanation}")

 FEATURE EXPLANATIONS

  N  (Nitrogen)             → Promotes leafy, green growth. Essential for photosynthesis.
  P  (Phosphorus)           → Supports root development and flowering.
  K  (Potassium)            → Improves fruit quality and disease resistance.
  temperature               → Average temperature in °C. Crops have ideal temp ranges.
  humidity                  → Relative humidity in %. Affects plant transpiration.
  ph                        → Soil acidity (0-14). Most crops prefer 6.0-7.5.
  rainfall                  → Average rainfall in mm. Critical for water supply.
  label (TARGET)            → The crop name — this is what our model will PREDICT.

In [12]:
# This generates statistical summary of all NUMERICAL columns automatically
print(" DESCRIPTIVE STATISTICS ")
df.describe()

 DESCRIPTIVE STATISTICS

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [13]:
# This shows all distinct crop names in the column
print(" ALL CROP TYPES ")
print(df['label'].unique())

print("\n NUMBER OF UNIQUE CROPS ")
print(df['label'].nunique())

 ALL CROP TYPES
<StringArray>
[       'rice',       'maize',    'chickpea', 'kidneybeans',  'pigeonpeas',
   'mothbeans',    'mungbean',   'blackgram',      'lentil', 'pomegranate',
      'banana',       'mango',      'grapes',  'watermelon',   'muskmelon',
       'apple',      'orange',      'papaya',     'coconut',      'cotton',
        'jute',      'coffee']
Length: 22, dtype: str

 NUMBER OF UNIQUE CROPS
22

In [14]:
# This counts how many rows exist for each crop - shows balance
print("\n SAMPLES PER CROP ")
print(df['label'].value_counts())

 SAMPLES PER CROP
label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

In [15]:
# Access a single column using column name
print(" NITROGEN COLUMN (first 5 values) ")
print(df['N'].head())

 NITROGEN COLUMN (first 5 values)
0    90
1    85
2    60
3    74
4    78
Name: N, dtype: int64

In [16]:
# Access a specific row using .iloc[row_number]
# iloc = integer location
print("\n ROW 0 (first record) ")
print(df.iloc[0])

 ROW 0 (first record)
N                      90
P                      42
K                      43
temperature     20.879744
humidity        82.002744
ph               6.502985
rainfall       202.935536
label                rice
Name: 0, dtype: object

In [18]:
# Access a specific cell: row 0, column 'label'
print("\n CROP NAME FOR ROW 0 ")
print(df.iloc[0]['label'])

 CROP NAME FOR ROW 0
rice

In [21]:
print ("shape:")
df.shape

shape:

(2200, 8)