In [2]:
# ============================================
# CROP RECOMMENDATION SYSTEM
# Phase 3 — Dataset Collection & Understanding
# ============================================

In [1]:
# Test that all libraries are working
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.ensemble import RandomForestClassifier

print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)
print("scikit-learn version:", sklearn.__version__)
print("All systems go! ✅")

pandas version: 3.0.2
numpy version: 2.4.4
scikit-learn version: 1.8.0
All systems go! ✅

In [3]:
# Import the libraries we need for this phase
import pandas as pd      # for loading and working with our dataset
import numpy as np       # for numerical operations

# -------------------------------------------
# Load the dataset from the data/ folder
# -------------------------------------------
# pd.read_csv() reads a CSV file and converts it
# into a DataFrame — pandas' version of a table
df = pd.read_csv('../data/crop_data.csv')

# Confirm it loaded successfully
print("Dataset loaded successfully!")
print("Shape:", df.shape)   # (rows, columns)

Dataset loaded successfully!
Shape: (2200, 8)

In [4]:
# -------------------------------------------
# .head() shows the FIRST 5 rows by default
# This gives us a quick peek at what the data looks like
# -------------------------------------------
print("=== FIRST 5 ROWS ===")
df.head()

=== FIRST 5 ROWS ===

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [5]:
# -------------------------------------------
# .tail() shows the LAST 5 rows
# Useful to check if data ends cleanly
# -------------------------------------------
print("=== LAST 5 ROWS ===")
df.tail()

=== LAST 5 ROWS ===

        N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [6]:
# -------------------------------------------
# .info() gives a full summary of the dataset:
# - Column names
# - How many non-null (non-missing) values exist
# - Data type of each column
# -------------------------------------------
print("=== DATASET INFO ===")
df.info()

=== DATASET INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB

In [ ]:
# -------------------------------------------
# .columns shows all column names in the dataset
# -------------------------------------------
print("=== COLUMN NAMES ===")
print(df.columns.tolist())

# -------------------------------------------
# .dtypes shows the data type of each column
# -------------------------------------------
print("\n=== DATA TYPES ===")
print(df.dtypes)

In [1]:
# ============================================
# CROP RECOMMENDATION SYSTEM
# Phase 4 — Data Preprocessing
# ============================================

# Import libraries
import pandas as pd      # data manipulation
import numpy as np       # numerical operations

# Load the dataset again (always reload at start of new phase)
df = pd.read_csv('../data/crop_data.csv')

print("Dataset loaded!")
print("Shape:", df.shape)

Dataset loaded!
Shape: (2200, 8)

In [2]:
# -------------------------------------------
# .isnull() checks every cell for missing values
# .sum() counts how many are missing per column
# -------------------------------------------
print("=== MISSING VALUES PER COLUMN ===")
missing = df.isnull().sum()
print(missing)

print("\n=== TOTAL MISSING VALUES ===")
print(missing.sum())

# -------------------------------------------
# Show percentage of missing values per column
# Helps decide how serious the problem is
# -------------------------------------------
print("\n=== MISSING VALUE PERCENTAGE ===")
missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent)

=== MISSING VALUES PER COLUMN ===
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

=== TOTAL MISSING VALUES ===
0

=== MISSING VALUE PERCENTAGE ===
N              0.0
P              0.0
K              0.0
temperature    0.0
humidity       0.0
ph             0.0
rainfall       0.0
label          0.0
dtype: float64

In [3]:
# -------------------------------------------
# .duplicated() marks every duplicate row as True
# .sum() counts how many duplicates exist
# -------------------------------------------
print("=== NUMBER OF DUPLICATE ROWS ===")
duplicates = df.duplicated().sum()
print(duplicates)

# -------------------------------------------
# Show the actual duplicate rows if any exist
# -------------------------------------------
print("\n=== DUPLICATE ROWS (if any) ===")
print(df[df.duplicated()])

=== NUMBER OF DUPLICATE ROWS ===
0

=== DUPLICATE ROWS (if any) ===
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []

In [4]:
# -------------------------------------------
# Check that all feature columns are numbers
# and label column is text (object)
# -------------------------------------------
print("=== DATA TYPES ===")
print(df.dtypes)

print("\n=== SHAPE CONFIRMATION ===")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

=== DATA TYPES ===
N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label              str
dtype: object

=== SHAPE CONFIRMATION ===
Rows: 2200
Columns: 8

In [5]:
# -------------------------------------------
# X = all columns EXCEPT the label column
# These are our 7 input features
# df.drop() removes the 'label' column
# axis=1 means we're dropping a COLUMN (not a row)
# -------------------------------------------
X = df.drop('label', axis=1)

# -------------------------------------------
# y = ONLY the label column
# This is what our model will predict
# -------------------------------------------
y = df['label']

# Confirm the separation worked correctly
print("=== FEATURES (X) ===")
print("Shape:", X.shape)
print("Columns:", X.columns.tolist())

print("\n=== TARGET (y) ===")
print("Shape:", y.shape)
print("First 5 values:", y.head().tolist())

=== FEATURES (X) ===
Shape: (2200, 7)
Columns: ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']

=== TARGET (y) ===
Shape: (2200,)
First 5 values: ['rice', 'rice', 'rice', 'rice', 'rice']

In [6]:
# -------------------------------------------
# Import train_test_split from scikit-learn
# This function automatically splits our data
# -------------------------------------------
from sklearn.model_selection import train_test_split

# -------------------------------------------
# Split the data:
# test_size=0.2    → 20% goes to testing, 80% to training
# random_state=42  → fixes the random split so we get
#                    the same split every time we run
#                    (makes results reproducible)
# stratify=y       → ensures all 22 crops are represented
#                    proportionally in both train and test sets
# -------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,              # input features
    y,              # target labels
    test_size=0.2,  # 20% for testing
    random_state=42,# reproducible split
    stratify=y      # balanced crop distribution
)

# -------------------------------------------
# Confirm the split worked correctly
# -------------------------------------------
print("=== TRAIN/TEST SPLIT RESULTS ===")
print(f"Total samples       : {len(X)}")
print(f"Training samples    : {len(X_train)} ({len(X_train)/len(X)*100:.0f}%)")
print(f"Testing samples     : {len(X_test)} ({len(X_test)/len(X)*100:.0f}%)")

print("\n=== SHAPES ===")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape : {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape : {y_test.shape}")

=== TRAIN/TEST SPLIT RESULTS ===
Total samples       : 2200
Training samples    : 1760 (80%)
Testing samples     : 440 (20%)

=== SHAPES ===
X_train shape: (1760, 7)
X_test shape : (440, 7)
y_train shape: (1760,)
y_test shape : (440,)

In [7]:
# -------------------------------------------
# Check crop distribution in training set
# Each crop should have ~80 samples (80% of 100)
# -------------------------------------------
print("=== CROP DISTRIBUTION IN TRAINING SET ===")
print(y_train.value_counts().sort_index())

print("\n=== CROP DISTRIBUTION IN TESTING SET ===")
# Each crop should have ~20 samples (20% of 100)
print(y_test.value_counts().sort_index())

=== CROP DISTRIBUTION IN TRAINING SET ===
label
apple          80
banana         80
blackgram      80
chickpea       80
coconut        80
coffee         80
cotton         80
grapes         80
jute           80
kidneybeans    80
lentil         80
maize          80
mango          80
mothbeans      80
mungbean       80
muskmelon      80
orange         80
papaya         80
pigeonpeas     80
pomegranate    80
rice           80
watermelon     80
Name: count, dtype: int64

=== CROP DISTRIBUTION IN TESTING SET ===
label
apple          20
banana         20
blackgram      20
chickpea       20
coconut        20
coffee         20
cotton         20
grapes         20
jute           20
kidneybeans    20
lentil         20
maize          20
mango          20
mothbeans      20
mungbean       20
muskmelon      20
orange         20
papaya         20
pigeonpeas     20
pomegranate    20
rice           20
watermelon     20
Name: count, dtype: int64

In [8]:
# -------------------------------------------
# Print a simple explanation of key concepts
# -------------------------------------------

concepts = {
    "Overfitting" : (
        "Model memorizes training data TOO well.\n"
        "    Works perfectly on training data.\n"
        "    Fails badly on new/test data.\n"
        "    Like a student who memorizes answers without understanding."
    ),
    "Underfitting": (
        "Model is TOO simple to learn patterns.\n"
        "    Performs poorly on BOTH training AND test data.\n"
        "    Like a student who didn't study at all."
    ),
    "Good Fit"    : (
        "Model learns patterns WITHOUT memorizing.\n"
        "    Performs well on BOTH training AND test data.\n"
        "    This is what we're aiming for!"
    )
}

print("=== MODEL FITTING CONCEPTS ===\n")
for concept, explanation in concepts.items():
    print(f"  {concept}:")
    print(f"    {explanation}\n")

=== MODEL FITTING CONCEPTS ===

  Overfitting:
    Model memorizes training data TOO well.
    Works perfectly on training data.
    Fails badly on new/test data.
    Like a student who memorizes answers without understanding.

  Underfitting:
    Model is TOO simple to learn patterns.
    Performs poorly on BOTH training AND test data.
    Like a student who didn't study at all.

  Good Fit:
    Model learns patterns WITHOUT memorizing.
    Performs well on BOTH training AND test data.
    This is what we're aiming for!